base_local_planner: base_local_planner/TrajectoryPlannerROS
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.12
  min_vel_x: 0.12
  max_vel_theta:  0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.5

  acc_lim_x: 0.12
  acc_lim_y: 0.0
  acc_lim_theta: 0.1

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.0
  vx_samples: 3
  vtheta_samples: 10
  sim_granularity: 0.025
  meter_scoring: true
  # heading_lookahead: 0.5
