obstacle_range: 1.0
raytrace_range: 3.0
robot_radius: 0.127
inflation_radius: 0.1

observation_sources: laser_scan_sensor

#point_cloud_sensor: {sensor_frame: laser_frame, data_type: PointCloud2, topic: cloud, marking: true, clearing: true}

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
