local_costmap:
    global_frame: odom
    robot_base_frame: chassis
    update_frequency: 10.0
    publish_frequency: 10.0
    static_map: true
    rolling_window: true
    width: 3.0
    height: 3.0
    origin_x: -1.5
    origin_y: -1.5
    resolution: 0.05
    transform_tolerance: 10.0
