
# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
          
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


mobile_base_controller:
  type: diff_drive_controller/DiffDriveController
  publish_rate: 50

  left_wheel: 'front_left_wheel_joint'
  right_wheel: 'front_right_wheel_joint'

  enable_odom_tf: false

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.108
  wheel_radius : 0.03175

  # Odometry covariances for the encoder output of the robot. These values should
  # be tuned to your robot's sample odometry data, but these values are a good place
  # to start
  pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 99.0]
  twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 99.0]

  # Top level frame (link) of the robot description
  base_frame_id: chassis

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.3   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.6   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # rad/s^2
